name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: PR Title Validation
        uses: ./.github/actions/pr-title-validator-action
        with:
          pr-title: ${{ github.event.pull_request.title }}
